Repository katzenpost/katzenpost, pull requests merged in 2022-11, with the labels that each got.

#70 fix panda client.Exchange spinning on error sending
  panda/client/client.go
Labels: pq-blocker

#69 Fix make clean
  docker/Makefile
Labels: pq-blocker

#75 This PR fixes a few more blocking channel operations in minclient and catshadow
  catshadow/client.go
  client/session.go
  minclient/connection.go
Labels: pq-blocker

#101 Pq sphinx
  core/sphinx/commands/commands_vectors_test.go
  core/sphinx/commands/testdata/sphinx_commands_vectors.json
  core/sphinx/internal/crypto/crypto.go
  core/sphinx/internal/crypto/crypto_test.go
  core/sphinx/sphinx.go
  core/sphinx/testdata/sphinx_vectors.json
  core/wire/commands/commands_vectors_test.go
  core/wire/commands/testdata/wire_commands_vectors.json
Labels: enhancement, security, cryptography, Post Quantum

#96 Fix cgo sphincs
  .github/scripts/install_sphincs.sh
  .github/workflows/go.yml
  README.rst
  catshadow/Makefile
  client/Makefile
  core/crypto/sign/ed25519sphincsplus/scheme.go
  core/crypto/sign/sphincsplus/sphincs.go
  docker/Makefile
  memspool/Makefile
  server/Makefile
  sphincsplus/ref/binding.go
  sphincsplus/ref/binding_test.go
  sphincsplus/ref/params/params.go
  sphincsplus/ref/raft/PQCgenKAT_sign.c
  sphincsplus/ref/raft/haraka.c
  sphincsplus/ref/raft/haraka.h
  sphincsplus/ref/raft/haraka_offsets.h
  sphincsplus/ref/raft/hash_haraka.c
  sphincsplus/ref/raft/hash_sha2.c
  sphincsplus/ref/raft/rng.c
  sphincsplus/ref/raft/sha2.c
  sphincsplus/ref/raft/sha2.h
  sphincsplus/ref/raft/sha2_offsets.h
  sphincsplus/ref/raft/thash_haraka_robust.c
  sphincsplus/ref/raft/thash_haraka_simple.c
  sphincsplus/ref/raft/thash_sha2_robust.c
  sphincsplus/ref/raft/thash_sha2_simple.c
  sphincsplus/ref/raft/thash_shake_simple.c
  sphincsplus/ref/vector_test.go
  sphincsplus_cgo/LICENSE
  sphincsplus_cgo/README.md
Labels: enhancement

#104 Fix voting auth cert db bug
  authority/internal/s11n/descriptor.go
  authority/internal/s11n/document.go
Labels: bug
