Repository katzenpost/katzenpost, pull requests merged in 2024-05, with the labels that each got.

#573 core/pki: get rid of Transport type alias
  authority/voting/client/client_test.go
  authority/voting/server/state_test.go
  client/config/config.go
  core/pki/descriptor.go
  core/pki/descriptor_test.go
  core/pki/document.go
  core/pki/document_test.go
  minclient/client.go
  server/config/config.go
  server/internal/decoy/decoy_test.go
  server/internal/pki/pki.go
Labels: enhancement

#589 fix TestKeyExchangeWithSerialization
  panda/crypto/panda_test.go
Labels: bug

#596 add CI testing matrix, make it work on Linux, Mac and Windows
  .github/workflows/go.yml
  .github/workflows/windows-msys-64bit-gcc-ucrt-msvcrt-golang-test.yml
  authority/cmd/voting/main.go
  authority/voting/client/client_test.go
  authority/voting/server/state_test.go
  bench/bench_test.go
  catshadow/client.go
  catshadow/client_test.go
  catshadow/contact.go
  catshadow/disk.go
  client/config/config.go
  core/cert/cert_test.go
  core/compat/umask.go
  core/compat/umask_not_supported.go
  core/pki/descriptor_test.go
  core/pki/document_test.go
  core/wire/commands/commands_test.go
  doubleratchet/README.rst
  doubleratchet/constants.go
  doubleratchet/ratchet.go
  doubleratchet/ratchet_test.go
  genconfig/main.go
  go.mod
  go.sum
  minclient/connection.go
  reunion/crypto/crypto_test.go
  reunion/crypto/elligator.go
  reunion/crypto/session.go
  reunion/crypto/session_benchmark_test.go
  reunion/crypto/session_test.go
  reunion/crypto/sprp.go
  server/cmd/server/main.go
  server/config/config_test.go
  server/internal/decoy/decoy_test.go
  server/internal/service/kaetzchen/kaetzchen_test.go
  server/server_shutdown_test.go
Labels: compatibility

#580 add goreleaser
  .github/workflows/darwin.yml
  .github/workflows/go.yml
  .github/workflows/linux.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
Labels: enhancement

#614 Fix ratchet (CI redux)
  .github/workflows/darwin.yml
  .github/workflows/docker-mixnet.yml
  .github/workflows/linux.yml
  .github/workflows/release.yml
  .github/workflows/windows-msys-64bit-gcc-ucrt-msvcrt-golang-test.yml
  catshadow/client.go
  catshadow/contact.go
  doubleratchet/constants.go
  doubleratchet/ratchet.go
  doubleratchet/ratchet_test.go
  genconfig/main.go
  go.mod
  go.sum
  reunion/server/server.go
  reunion/servers/reunion_http_server/server_test.go
Labels: bug

#591 Fix packet dropping bug
  server/internal/cryptoworker/crypto_worker.go
Labels: bug
